"""empty message

Revision ID: 10c01bc28c51
Revises: 700b2235559d
Create Date: 2021-03-09 04:01:34.844426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c01bc28c51'
down_revision = '700b2235559d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('uq_user_useridx', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_userid'), ['userid'])
        batch_op.drop_column('useridx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useridx', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_user_userid'), type_='unique')
        batch_op.create_unique_constraint('uq_user_useridx', ['useridx'])
        batch_op.drop_column('userid')

    # ### end Alembic commands ###
